version: "3.9"

services:
  nginx:
    hostname: AwsomiumApp
    container_name: nginx
    build: ./nginx
    ports:
      - "80:80"
  ######
  elasticsearch:
    hostname: elastic
    container_name: elastic
    build: ./elastic
    volumes:
      - "elasticdata:/usr/share/elasticsearch/data:rw"
    environment:
     - bootstrap.memory_lock=true
     - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
  ######
  logstash:
    hostname: logstash
    container_name: logstash
    build: ./logstash
    ports:
      - 5044:5044
    environment:
     LOG_LEVEL: error
  ######
  kibana:
    hostname: Kibana  
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.9.3
    environment:
     - "LOGGING_QUIET=true"
    ports:
      - 5601:5601      
  ######   
  filebeat:
    hostname: Filebeat
    container_name: filebeat
    build: ./filebeat
    volumes:
     - "/var/lib/docker/containers:/usr/share/dockerlogs/data:ro"
     - "/var/run/docker.sock:/var/run/docker.sock"
volumes:
  elasticdata: